project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.qmd"

execute:
  freeze: auto
  
website:
  title: "W3TM"
  site-url: https://w3tm.org
  description: "W3TM's ham radio blog"
  navbar:
    left:
      - index.qmd
      - preface.qmd
      - organizations.qmd
      - events.qmd
      - education.qmd
      - workbench.qmd
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        text: Github
        href: https://github.com/W3TM/
format:
  html:
    theme: zephyr
    number-sections: false
    fig-align: center
    toc: true
    toc-depth: 3
