---
title: "IC-9700"
---

This page describes some mode-specific settings for the IC-9700 station.

## Manuals

Manuals for the IC-9700 can be found here:

- [Basic](icom-IC-9700_ENG_Basic_3.pdf)
- [Advanced](icom-IC-9700_ENG_AM_1.pdf)

## APRS-tt

### Hardware

#### Rig

- IC-9700
- USB A/B cable

::: {.callout-note}

Frequency: 146.580 MHz</br>
Mode: FM-D (digital)

*Connectors/*</br>
USB AF/IF Output/Output Select: `AF`</br>
USB AF/IF Output/AF Output Level: `50%`</br>
MOD Input/DATA MOD: `USB`</br>
USB Send/KEYING/USB SEND: `USB (A) RTS`</br>
USB Send/KEYING/Inhibit Timer at USB Connection: `ON`</br>
CI-V/CI-V DATA Echo Back: `ON`</br>
PTT Port Function: `PTT Input + SEND Output`

:::

#### PC

- Acer Windows 10 laptop

#### Antenna

- Comet antenna mounted externally
- Connected via coax patch panel

### Software

#### PC System Settings

::: {.callout-note}

\# Right click Windows icon; select 'Device Manager'; Select 'Ports (COM & LPT)'</br>
`Silicon Labs SP210x USB to UART Bridge (COM4)`</br>

\# Right click Windows icon; select 'Device Manager'; Select 'Audio inputs and outputs'</br>
`IC-9700 (4- USB Audio CODEC)`</br>
`Microphone (4- USB Audio CODEC)`

\# Enter 'control panel' in search window; Open 'Hardware and Sound'; Select 'Sound'

\# Under 'Recording' tab
1. Confirm that Microphone (4- USB Audio CODEC) is *not* default device
2. Click Properties button; select Levels tab
3. Set Microphone level to ~65% (adjust as needed)

#\ Under 'Playback' tab
1. Confirm that IC-9700 is *not* default device
2. Click Properties button; select Levels tab
3. Set Speakers slider to ~50%

::: 

#### Application

- Direwolf 1.7

::: {.callout-note}

Parameters in `direwolf.conf`

ADEVICE (4- USB

CHANNEL 0

MYCALL W3TM-8

MODEM 1200

DTMF

PTT COM4 RTS

AGWPORT 8000</br>
KISSPORT 8001

CBEACON every=10 dest="MORSE-6" info="de W3TM-tt"

IGSERVER noam.aprs2.net

\# Logged-in to APRS-IS to send packets.</br>
IGLOGIN W3TM-8 28828

IGTXLIMIT 6 10

TTPOINT B001 40.7177087 -77.891919  # mountaintop</br>
TTPOINT B002 40.7753191 -77.8561127 # South Hills</br>
TTPOINT B003 40.8055434 -77.88982   # Hoss'</br>
TTPOINT B085 40.753017  -77.760620  # Little Flat 85</br>
TTPOINT B076 40.9123402 -78.019739  # Rattlesnake 76</br>

TTAMBIG BAx

\# W3TM</br>
TTMACRO 001xx AC9386001109*AB{dot}*B0xx*BA1</br>
\# W3EDP ------------------------------------</br>
TTMACRO 011xx AC9333701173*AB{dot}*B0xx*BA1</br>
\# N3LI ------------------------------------</br>
TTMACRO 021xx AC6354002293*AB{dot}*B0xx*BA1</br>
\# W3SWL</br>
TTMACRO 031xx AC9379501245*AB{dot}*B0xx*BA1</br>
\# WA7HUB</br>
TTMACRO 041xx AC9274821322*AB{dot}*B0xx*BA1</br>

TTOBJ 0 IG</br>
CHANNEL 0</br>
DWAIT 100</br>

:::

### Operating

1. Switch to 145.80 MHz, FM-D mode. **Note:** Memory channel 10 has this frequency but not FM-D stored!
2. Launch Direwolf from desktop
3. Confirm that Direwolf has connected to audio devices.
4. Enter DTMF tones to test or switch to 144.390 MHz to ensure that packets are being decoded.

## Winlink

#### Rig

- IC-9700
- USB A/B cable

::: {.callout-note}

Frequency: 145.090 MHz (this frequency is stored in one of the memories)</br>
Mode: FM-D (digital)

*Connectors/*</br>
USB AF/IF Output/Output Select: `AF`</br>
USB AF/IF Output/AF Output Level: `50%`</br>
MOD Input/DATA MOD: `USB`</br>
USB Send/KEYING/USB SEND: `USB (A) RTS`</br>
USB Send/KEYING/Inhibit Timer at USB Connection: `ON`</br>
CI-V/CI-V DATA Echo Back: `ON`</br>
PTT Port Function: `PTT Input + SEND Output`
:::

#### PC

- Acer Windows 10 laptop

#### Antenna

- Comet antenna mounted externally
- Connected via coax patch panel

### Software

#### PC System Settings

::: {.callout-note}

\# Right click Windows icon; select Device Manager; Select Ports (COM & LPT)
`Silicon Labs SP210x USB to UART Bridge (COM4)`</br>

\# Right click Windows icon; select Device Manager; Select Audio inputs and outputs
`IC-9700 (4- USB Audio CODEC)`</br>
`Microphone (4- USB Audio CODEC)`

\# Enter 'control panel' in search window; Open Hardware and Sound; Select Sound

\# Under Recording tab
1. Confirm that Microphone (4- USB Audio CODEC) is *not* default device
2. Click Properties button; select Levels tab
3. Set Microphone level to ~65% (adjust as needed)

#\ Under Playback tab
1. Confirm that IC-9700 is *not* default device
2. Click Properties button; select Levels tab
3. Set Speakers slider to ~50%

::: 

#### Application

- Winlink Express 1.7.12.0

::: {.callout-note}

Winlink Express parameters.

\# Settings : Winlink Express Setup</br>
My Callsign: `W3TM`</br>
My Password: `*******`</br>
Password recovery email: `rogilmore@mac.com`
My Grid Square `FN10BT`</br>
Winlink Express registration key: `HIDDEN`</br>

There are many other parameters but these are the most important ones.

:::

- VARA FM

::: {.callout-note}

\# Under Settings
**VARA Setup...**</br>
TCP Ports: Command: `8300`</br>
TCP Ports: Data: `8301`</br>

FM System: `NARROW`</br>
Digipeater: </br>
Retries: `2`</br>

VARA Licenses:</br>
Callsign: `W3TM`</br>
Registration Key: `*******`

**Soundcard...**</br>
Device Input: `Microphone (4- USB Audio CODEC)`</br>
Device Output: `IC-9700 (4- USB Audio CODEC)`

**PTT...**</br>
PTT Via: `CAT'</br>
Brand: `Icom`</br>
Port: `COM4`</br>
Model: `IC-9700`</br>
Baud: `19200`</br>
CI-V Address: `A2`

Oddly enough, RTS is *unchecked*.

:::

### Operating

1. Switch to memory channel 11 (145.090 MHz, W3SWL-10), FM-D mode
2. Launch Winlink Express from desktop
3. Open Session: Vara FM Winlink
4. Check rig RF power (10W is more than sufficient)
5. When Var FM Winlink Session window opens, confirm that W3SWL-10 @ 145.090 is selected
6. Press **Start** button to initiate QSO.
7. Turn up AF gain to monitor QSO. You will hear sound from W3SWL-10, but not the output

## Packet

#### Rig

- IC-9700
- USB A/B cable

::: {.callout-note}

Frequency: 145.030 MHz (this frequency is stored in one of the memories)</br>
Mode: FM-D (digital)

The following settings do not change from Winlink or APRS-tt (via Direwolf)

*Connectors/*</br>
USB AF/IF Output/Output Select: `AF`</br>
USB AF/IF Output/AF Output Level: `50%`</br>
MOD Input/DATA MOD: `USB`</br>
USB Send/KEYING/USB SEND: `USB (A) RTS`</br>
USB Send/KEYING/Inhibit Timer at USB Connection: `ON`</br>
CI-V/CI-V DATA Echo Back: `ON`</br>
PTT Port Function: 'PTT Input + SEND Output`
:::

#### PC

- Acer Windows 10 laptop

#### Antenna

- Comet antenna mounted externally
- Connected via coax patch panel

### Software

#### PC System Settings

::: {.callout-note}

The following settings should not change from those for Winlink Express or APRS-tt.

\# Right click Windows icon; select Device Manager; Select Ports (COM & LPT)
`Silicon Labs SP210x USB to UART Bridge (COM4)`</br>

\# Right click Windows icon; select Device Manager; Select Audio inputs and outputs
`IC-9700 (4- USB Audio CODEC)`</br>
`Microphone (4- USB Audio CODEC)`

\# Enter 'control panel' in search window; Open Hardware and Sound; Select Sound

\# Under Recording tab
1. Confirm that Microphone (4- USB Audio CODEC) is *not* default device
2. Click Properties button; select Levels tab
3. Set Microphone level to ~65% (adjust as needed)

#\ Under Playback tab
1. Confirm that IC-9700 is *not* default device
2. Click Properties button; select Levels tab
3. Set Speakers slider to ~50%

::: 

#### Application

- UZ7HO version 1.13 SoundModem

::: {.callout-note}

SoundModem parameters.

\# Settings menu: Devices
Sound Card: Output device: `IC-9700 (4-USB Audio CODEC)`</br>
Sound Card: Input device: `Microphone (4-USB Audio CODEC)`</br>
Sound Card: Single channel output</br>
Sound Card: Color waterfall</br>

Server setup: AGWPE Server Port: `8000` and `Enabled`
Server setup: KISS Server Port: `8001`

PTT Port: Select PTT port: `COM4`

\# Settings menu: Modems

:::

- EasyTerm by UZ7HO Version 0.49b

::: {.callout-note}

EasyTerm parameters.

\# Settings menu: Station Setup</br>
Terminal Callsign: `W3TM`</br>

Beacon Setup: Destination: `BEACON`</br>
Beacon Setup: Interval: `30`</br>
Beacon Setup: Ports: `1'</br>

TNC Setup: Host: `127.0.0.1`</br>
TNC Setup: Port: `8000`</br>
TNC Setup: Paclen: `80`

:::

### Operating

1. Switch to memory channel 7 (145.030 MHz, W3YA-3 Packet), FM-D mode
2. Launch SoundModem.
3. Launch EasyTerm
4. Check rig RF power (10W is more than sufficient)
5. W3YA-3 and W3PHB-3 beacon regularly, so it's good to see if you can decode them.
6. When the channel is clear, press the 'Connect' button
7. Select target from 'CallTo' menu, usually `W3YA-3` or `W3PHB-3`
8. Press the 'Connect' button to connect.
7. Turn up AF gain to monitor QSO. You will hear sound from the packet BBS, but not your own output (unless you have turned up the monitor level on the rig).
